{{- range $name, $options:= .Values.deployments }}
{{- if and $options.autoscaleEnabled $options.autoscaleMin $options.autoscaleMax }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}
  namespace: {{ $options.namespace | default $.Release.Namespace }}
  labels:
{{ .labels | toYaml | indent 4 }}
    release: {{ $.Release.Name }}
    istio.io/rev: {{ $.Values.revision | default "default" }}
    install.operator.istio.io/owning-resource: {{ $.Values.ownerName | default "unknown" }}
    operator.istio.io/component: "IngressGateways"
spec:
  maxReplicas: {{ $options.autoscaleMax }}
  minReplicas: {{ $options.autoscaleMin }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $name }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ $options.cpu.targetAverageUtilization }}
{{- end }}
{{- end }}
