{{- range $name, $options:= .Values.deployments }}
---
apiVersion: v1
kind: ServiceAccount
{{- if $.Values.global.imagePullSecrets }}
imagePullSecrets:
{{- range $.Values.global.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}
metadata:
  name: {{ $name }}-service-account
  namespace: {{ $options.namespace | default $.Release.Namespace }}
  labels:
{{ .labels | toYaml | trim | indent 4 }}
    release: {{ $.Release.Name }}
    istio.io/rev: {{ $.Values.revision | default "default" }}
    install.operator.istio.io/owning-resource: {{ $.Values.ownerName | default "unknown" }}
    operator.istio.io/component: "IngressGateways"
{{- end }}
