# MIT License
# (C) Copyright [2020-2021] Hewlett Packard Enterprise Development LP
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

---
hub: artifactory.algol60.net/csm-docker/stable/istio
tag: 1.8.6-cray2-distroless   # Also update the proxyv2 annotations in Chart.yaml

kubectl:
  image:
    repository: artifactory.algol60.net/csm-docker/stable/docker-kubectl
    tag: 1.19.15

pilot:
  hub: artifactory.algol60.net/csm-docker/stable/istio
  tag: 1.8.6-cray2-distroless   # Also update the pilot annotations in Chart.yaml
  resources:
    requests:
      cpu:
      memory:

meshConfig:
  accessLogFile: /dev/stdout

istio:

  global:
    imagePullPolicy: IfNotPresent
    priorityClassName: csm-high-priority-service

  sidecarInjectorWebhook:
    rewriteAppHTTPProbe: true

  galley:
    enabled: false

  gateways:
    istio-ingressgateway:
      enabled: false  # This is disabled here to work around limitation of istio 1.5. It's enabled in the cray-istio chart.
      type: LoadBalancer
      autoscaleEnabled: true
      autoscaleMin: 2
      autoscaleMax: 5
      ports:
      - port: 80
        name: http2
      - port: 443
        name: https
      env:
        ISTIO_META_IDLE_TIMEOUT: 10m

  tracing:
    enabled: false

  pilot:
    env:
      USE_ISTIO_JWT_FILTER: "true"
      PILOT_ENABLE_UNSAFE_REGEX: "true"
