#
# MIT License
#
# (C) Copyright 2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: v2
version: 1.23.2
name: cray-istio-operator
description: Helm chart for deploying Istio operator
keywords:
  - istio
  - operator
home: https://github.com/Cray-HPE/cray-istio
sources:
  - https://github.com/Cray-HPE/cray-istio
dependencies:
  - name: istio-operator
    version: 1.7.0
maintainers:
  - name: brantk-hpe
appVersion: 1.8.6
annotations:
  artifacthub.io/images: |
    - name: istio-operator-distro
      image: artifactory.algol60.net/csm-docker/stable/istio/operator:1.8.6-cray2
  artifacthub.io/license: MIT
